### PR TITLE
initial code for stratigraphic classes

### PR DESCRIPTION
**Pull request by andy-beer**
This change introduces 5 more high level classes, in a new module named strata.py

The aim is for resqpy to be able to work with the stratigraphic objects exported from RMS.

resolves issue #175

### CODE REVIEW

**Comment by andy-beer** [comment]
Initial coding of strata.py module is complete in this branch.  Still to do:

- test module
- enhancements to Grid class to implement interval stratigraphic units (vector of integers indicating which unit index within a related stratigraphic column rank interpretation is applicable to each layer in the grid)

**Review by emmanesbit — COMMENTED** [review]
Hi Andy. These changes look good - i'm going to check loading the outputs into various applications before merging however. Will approve once i've done this.

**Comment by emmanesbit** [comment]
Hi Andy - i'm getting the below error on a couple of different applications. It seems unhappy about the GeologicUnitComposition type.

> "Validation constraint violation: type mismatch resqml2:GeologicUnitComposition in element 'resqml2:GeologicUnitComposition'"
> Detail: [no detail]
>  IN /obj_StratigraphicUnitInterpretation_866f5348-03f5-11ec-85cc-248a07af104a.xml.

**Comment by andy-beer** [comment]
@emmanesbit At a quick glance I can't see anything obviously wrong with the GeologicUnitComposition type – I'll have a more thorough look in the next day or so.

**Comment by andy-beer** [comment]
@emmanesbit Although I have not found any error in the type information for the geologic unit composition, I suspect the issue may have arisen due to the spurious trailing space included in two of the composition names in the RESQML xsd (namely 'intrusive clay ' and 'intrusive mud ').  I have made code changes to store these composition names with the trailing space in xml (whilst presenting the resqpy without the space to calling code).  Could you please re-run your interoperability tests. Thanks.

**Comment by andy-beer** [comment]
The stratigraphy code is being merged into master.  Note however that RESQML models with stratigraphy generated by resqpy have not yet been successfully loaded into non-resqpy applications.

**Pull request merged**
